name: Folders-root
 
# When to launch. During which event
on: push

jobs:
  gh-pages:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
        os: [macOS-latest, ubuntu-latest]

    steps:
      - name: repo
        uses: actions/checkout@v1  
         
      - name: list-repo
        run: ls -la
