name: Folders-root
 
# When to launch. During which event
on: push

jobs:
  gh-pages:
    runs-on: ubuntu-latest 
    
    steps:
      - name: clone
        uses: actions/checkout@v1     
         
         
      - name: open-sh 
        run: |   
             ls -la   
             chmod +x publish.sh
             cd example ./publish.sh 
             ls -la  
      
