name: Folders-root
 
# When to launch. During which event
on: push 
   
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

jobs:
  gh-pages:
    runs-on: ubuntu-latest 
    
    steps:
      - name: clone
        uses: actions/checkout@v1     
         
      - name: open-sh 
        run: |     
             export REPOSITORY_NAME=$(basename ${{ github.repository }}) 
             export GITHUB_TOKEN
             cd example  
             chmod +x publish.sh
             ./publish.sh    
           
      - name: publication 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          registry-url: https://registry.npmjs.org/
      - run: |  
         rm -rf ./example 
         npm i
         npm ci 
         npm run lint 
         npm run build
         npm publish --access public 
         
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
             
       
      
