name: CD

# When to launch. During which event
on: push 

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v1     
      - name: Publish to GitHub Pages 
        run: |     
             export REPOSITORY_NAME=$(basename ${{ github.repository }}) 
             cd example  
             chmod +x publish.sh
             ./publish.sh    
      - name: publication 
        run: | 
             npm i
             npm run lint 
             npm run build
             npm ci
             npm publish --access public 
              env:
               NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
