name: CD

# When to launch. During which event
on: push 

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Publish to GitHub Pages 
        run: |     
             export REPOSITORY_NAME=$(basename ${{ github.repository }}) 
             cd example  
             chmod +x publish.sh
             ./publish.sh    
      - name: Publish to NPM Registry
        run: | 
             npm i
             npm run lint 
             npm run build
             npm ci
             npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
